package fr.sethlans.core.render.vk.pipeline;

import org.lwjgl.vulkan.VK10;
import org.lwjgl.vulkan.VK13;

import fr.sethlans.core.render.vk.util.VkFlag;

public enum Access implements VkFlag<Access> {

    INDIRECT_COMMAND_READ(VK10.VK_ACCESS_INDIRECT_COMMAND_READ_BIT),
    
    INDEX_READ(VK10.VK_ACCESS_INDEX_READ_BIT),
    
    VERTEX_ATTRIBUTE_READ(VK10.VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT),
    
    UNIFORM_READ(VK10.VK_ACCESS_UNIFORM_READ_BIT),
    
    INPUT_ATTACHMENT_READ(VK10.VK_ACCESS_INPUT_ATTACHMENT_READ_BIT),
    
    SHADER_READ(VK10.VK_ACCESS_SHADER_READ_BIT),
    
    SHADER_WRITE(VK10.VK_ACCESS_SHADER_WRITE_BIT),
    
    COLOR_ATTACHMENT_READ(VK10.VK_ACCESS_COLOR_ATTACHMENT_READ_BIT),
    
    COLOR_ATTACHMENT_WRITE(VK10.VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT),
    
    DEPTH_STENCIL_ATTACHMENT_READ(VK10.VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT),
    
    DEPTH_STENCIL_ATTACHMENT_WRITE(VK10.VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT),
    
    TRANSFER_READ(VK10.VK_ACCESS_TRANSFER_READ_BIT),
    
    TRANSFER_WRITE(VK10.VK_ACCESS_TRANSFER_WRITE_BIT),
    
    HOST_READ(VK10.VK_ACCESS_HOST_READ_BIT),
    
    HOST_WRITE(VK10.VK_ACCESS_HOST_WRITE_BIT),
    
    MEMORY_READ(VK10.VK_ACCESS_MEMORY_READ_BIT),
    
    MEMORY_WRITE(VK10.VK_ACCESS_MEMORY_WRITE_BIT),
    
    NONE(VK13.VK_ACCESS_NONE);
    
    private final int bits;

    private Access(int bits) {
        this.bits = bits;
    }

    @Override
    public int bits() {
        return bits;
    }
}
