package fr.sethlans.core.render.vk.pipeline;

import org.lwjgl.vulkan.VK10;
import org.lwjgl.vulkan.VK13;
import org.lwjgl.vulkan.VK14;

public enum DynamicState {

    VIEWPORT(VK10.VK_DYNAMIC_STATE_VIEWPORT),
    
    SCISSOR(VK10.VK_DYNAMIC_STATE_SCISSOR),
    
    LINE_WIDTH(VK10.VK_DYNAMIC_STATE_LINE_WIDTH),
    
    DEPTH_BIAS(VK10.VK_DYNAMIC_STATE_DEPTH_BIAS),
    
    BLEND_CONSTANTS(VK10.VK_DYNAMIC_STATE_BLEND_CONSTANTS),
    
    DEPTH_BOUNDS(VK10.VK_DYNAMIC_STATE_DEPTH_BOUNDS),
    
    STENCIL_COMPARE_MASK(VK10.VK_DYNAMIC_STATE_STENCIL_COMPARE_MASK),
    
    STENCIL_WRITE_MASK(VK10.VK_DYNAMIC_STATE_STENCIL_WRITE_MASK),
    
    STENCIL_REFERENCE(VK10.VK_DYNAMIC_STATE_STENCIL_REFERENCE),
    
    CULL_MODE(VK13.VK_DYNAMIC_STATE_CULL_MODE),
    
    FRONT_FACE(VK13.VK_DYNAMIC_STATE_FRONT_FACE),
    
    PRIMITIVE_TOPOLOGY(VK13.VK_DYNAMIC_STATE_PRIMITIVE_TOPOLOGY),
    
    VIEWPORT_WITH_COUNT(VK13.VK_DYNAMIC_STATE_VIEWPORT_WITH_COUNT),
    
    SCISSOR_WITH_COUNT(VK13.VK_DYNAMIC_STATE_SCISSOR_WITH_COUNT),
    
    VERTEX_INPUT_BINDING_STRIDE(VK13.VK_DYNAMIC_STATE_VERTEX_INPUT_BINDING_STRIDE),
    
    DEPTH_TEST_ENABLE(VK13.VK_DYNAMIC_STATE_DEPTH_TEST_ENABLE),
    
    DEPTH_WRITE_ENABLE(VK13.VK_DYNAMIC_STATE_DEPTH_WRITE_ENABLE),
    
    DEPTH_COMPARE_OP(VK13.VK_DYNAMIC_STATE_DEPTH_COMPARE_OP),
    
    DEPTH_BOUNDS_TEST_ENABLE(VK13.VK_DYNAMIC_STATE_DEPTH_BOUNDS_TEST_ENABLE),
    
    STENCIL_TEST_ENABLE(VK13.VK_DYNAMIC_STATE_STENCIL_TEST_ENABLE),
    
    STENCIL_OP(VK13.VK_DYNAMIC_STATE_STENCIL_OP),
    
    RASTERIZER_DISCARD_ENABLE(VK13.VK_DYNAMIC_STATE_RASTERIZER_DISCARD_ENABLE),
    
    DEPTH_BIAS_ENABLE(VK13.VK_DYNAMIC_STATE_DEPTH_BIAS_ENABLE),
    
    PRIMITIVE_RESTART_ENABLE(VK13.VK_DYNAMIC_STATE_PRIMITIVE_RESTART_ENABLE),
    
    LINE_STIPPLE(VK14.VK_DYNAMIC_STATE_LINE_STIPPLE);
    
    private final int vkEnum;

    private DynamicState(int vkEnum) {
        this.vkEnum = vkEnum;
    }

    public int vkEnum() {
        return vkEnum;
    }
}
